version: '3.8'
services:
  oracle:
    image: gvenzl/oracle-free:slim
    container_name: oracle-for-javaspringboot-api
    environment:
      ORACLE_PASSWORD: password@123!
      APP_USER: sa
      APP_USER_PASSWORD: password@123!
    healthcheck:
      test: [ "CMD", "/opt/oracle/healthcheck.sh"]
      interval: 5s
      timeout: 5s
      retries: 20
    ports:
      - 1521:1521
    volumes:
      - javaspringboot-api-oracle-db-data:/opt/oracle/oradata
  javaspringboot-api-oracle:
    image: sample/javaspringboot-api
    container_name: javaspringboot-api-oracle
    ports:
      - 8080:8080
    depends_on:
      oracle:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=oracle
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@//oracle:1521/FREEPDB1
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=password@123!
volumes:
  javaspringboot-api-oracle-db-data: